# 2D Arrays

## Creation of 2D arrays

In [ ]:
# creating array directly
array = [[1, 2], [3, 4]]

print(array)

[[1, 2], [3, 4]]


In [3]:
# Using NumPy

import numpy as np

array = np.array([[1, 2], [3, 4]])

print(array)

[[1 2]
 [3 4]]


In [7]:
# Using NumPy to fill zeroes
rows = 2
cols = 3
array = np.zeros((rows, cols))

print(array)

# Using NumPy to fill ones
rows = 2
cols = 3
array = np.ones((rows, cols))

print(array)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# Using NumPy with np.full (for custom initialization)
rows = 2
cols = 3
array = np.full((rows, cols), 10)

print(array)

[[10 10 10]
 [10 10 10]]


## Accessing elements

A 2D array is a collection of data elements arranged in rows and columns. Accessing elements involves specifying their row and column indices.

In [8]:
# Using Indexing (Direct Access)

arr = [[1, 2], [3, 4]]
print(arr[0][1]) 

2


In [9]:
# Using Loops (Row and Column Iteration)

arr = [[1, 2], [3, 4]]
for i in range(len(arr)):
    for j in range(len(arr[i])):
        print(arr[i][j], end=" ")
    print()

1 2 
3 4 


In [10]:
import numpy as np
arr_np = np.array([[1, 2], [3, 4]])
print(arr_np[1, 0])  

3


## Modifying elements

In [11]:
# Direct Assignment

arr = [[1, 2], [3, 4]]
arr[0][1] = 10
print(arr)

[[1, 10], [3, 4]]


In [13]:
# using nested loops

arr = [[1, 2], [3, 4]]

for i in range(len(arr)):
    for j in range(len(arr[i])):
        arr[i][j] = arr[i][j] ** 2
print(arr)

[[1, 4], [9, 16]]


In [14]:
# Modifying with NumPy Array

import numpy as np

arr = np.array([[1, 2], [3, 4]])
arr[0, 1] = 10
print(arr)

[[ 1 10]
 [ 3  4]]


## Iterating with nested loops

In [19]:
# Using range() with indices

arr = [[1, 2], [3, 4]]
for i in range(len(arr)):
    for j in range(len(arr[i])):
        print(arr[i][j], end=" ")
    print()

1 2 
3 4 


In [ ]:
# using values directly
for row in arr:
    for val in row:
        print(val, end=" ")
    print()

1 2 
3 4 


In [23]:
# Using enumerate() to get indices and values

arr = [[1, 2], [3, 4]]

for i, row in enumerate(arr):
    for j, val in enumerate(row):
        print(f"Element at ({i},{j}): {val}")

Element at (0,0): 1
Element at (0,1): 2
Element at (1,0): 3
Element at (1,1): 4


In [24]:
arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
# row wise
for row in arr:
    for val in row:
        print(val, end=' ')
    print() 

1 2 3 
4 5 6 
7 8 9 


In [26]:
rows = len(arr)
cols = len(arr[0])

for col in range(cols):
    for row in range(rows):
        print(arr[row][col], end=' ')
    print()  # new line after each column


1 4 7 
2 5 8 
3 6 9 


In [28]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

n = len(matrix)

# Print main diagonal
print("Main Diagonal:")
for i in range(n):
    print(matrix[i][i], end=' ')
print()



Main Diagonal:
1 5 9 


### ...

In [ ]:
# Print off (secondary) diagonal
print("Off Diagonal:")
for i in range(n):
    print(matrix[i][n - 1 - i], end=' ')
print()

## List comprehension

In [30]:
# 1D list comprehension
arr = [i + 1 for i in range(5)]
print(arr)

[1, 2, 3, 4, 5]


In [ ]:
arr = [1, 2, 3, 4, 5]
l = [print(val) for val in arr]
# print(l)

1
2
3
4
5


In [42]:
matrix = [[j+1 for j in range(3)] for i in range(3)]
print(matrix)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [ ]:
matrix = [[3 * i + j + 1 for j in range(3)] for i in range(3)]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [44]:
# interesting way to print
arr = [1, 2, 3, 4, 5]

print(*arr)

1 2 3 4 5


In [47]:
# interesting way to print
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


print(*matrix)

[1, 2, 3] [4, 5, 6] [7, 8, 9]


### ...

In [ ]:
def greet(name, age):
    print(f"Hello, {name}! You are {age} years old.")

person = {'name': 'Alice', 'age': 30}

greet(**person)


## Slicing

In [52]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Get first 2 rows and first 2 columns
submatrix = [row[:2] for row in matrix[:2]]

print(submatrix)


[[1, 2], [4, 5]]


## Numpy Functions

In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [59]:
# Row sum: Sum elements along each row
print(np.sum(arr, axis=1))


[ 6 15 24]


In [60]:
# Column sum: Sum elements along each column
print(np.sum(arr, axis=0))

[12 15 18]


In [61]:
# Element-wise addition
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1 + arr2)  



[[ 6  8]
 [10 12]]


In [62]:
# Element-wise multiplication
print(arr1 * arr2)  

[[ 5 12]
 [21 32]]


In [63]:
# Matrix multiplication
print(arr1.dot(arr2))

[[19 22]
 [43 50]]


In [65]:
# Transpose
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.transpose(arr1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
